### ISSUE TITLE
setup hierarchical model

### ISSUE THREAD

**Issue by anne-urai** [kiante-fernandez/2023_choicehistory_HSSM#16]
old code for modelspec: https://github.com/anne-urai/2019_Urai_choice-history-ddm/blob/master/hddm_models.py#L178C1-L181C86 & https://github.com/anne-urai/2019_Urai_choice-history-ddm/blob/master/hddm_models.py#L178C1-L181C86

**Comment by anne-urai** [comment]
For now, set hierarchical to True for all parameters except `sv`, `sz`

**Comment by kiante-fernandez** [comment]
Updating these issues: We have opted to continue setting parameters that are not part of the simplest case to group-level estimates due to issues with prior specification and parameter estimation. We have not run the model that includes sv, or sz (which would require using the Black-box full DDM; a set of likelihoods we have not yet tested).
